# Generated by Django 3.2.6 on 2021-09-05 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='article',
            new_name='articles',
        ),
    ]
