# Generated by Django 3.2.6 on 2021-09-05 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_rename_article_group_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='articles',
            field=models.ManyToManyField(blank=True, to='main_app.Article'),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
