# Generated by Django 3.2.6 on 2021-09-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_group_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
