# Generated by Django 3.2.6 on 2021-09-05 23:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0011_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Reply',
        ),
    ]
