# Generated by Django 3.2.6 on 2021-09-09 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_rename_group_article_grouparticlereview_grouparticle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouparticlereview',
            old_name='conntent',
            new_name='content',
        ),
    ]
