# Generated by Django 3.2.6 on 2021-09-09 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_articlecreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleCreate',
        ),
    ]
