# Generated by Django 3.2.6 on 2021-09-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_delete_articlecreate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
    ]
