# Generated by Django 3.2.6 on 2021-09-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20210909_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouparticlereview',
            name='content',
            field=models.TextField(),
        ),
    ]
